# Generated by Django 2.0.3 on 2018-04-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picarter_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='', max_length=200),
        ),
    ]
